#cloud-config

# Install .Net Runtime 8.0
runcmd:
  # Register Microsoft repository (which includes .Net Runtime 8.0 package)
  - wget -q https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
  - dpkg -i packages-microsoft-prod.deb

  # Install .Net Runtime 8.0
  - apt-get update
  - apt-get install -y aspnetcore-runtime-8.0

# Create a service for the application
write_files:
  - path: /etc/systemd/system/CloudSoft.service
    content: |
      [Unit]
      Description=ASP.NET Web App running on Ubuntu

      [Service]
      WorkingDirectory=/opt/CloudSoft
      ExecStart=/usr/bin/dotnet /opt/CloudSoft/CloudSoft.dll
      Restart=always
      RestartSec=10
      KillSignal=SIGINT
      SyslogIdentifier=CloudSoft
      User=www-data
      Environment=ASPNETCORE_ENVIRONMENT=Production
      Environment=DOTNET_PRINT_TELEMETRY_MESSAGE=false
      Environment="ASPNETCORE_URLS=http://*:5000"

      [Install]
      WantedBy=multi-user.target      
    owner: root:root
    permissions: '0644'

    
deploy:
    runs-on: self-hosted
    needs: build

    steps:
    - name: Download the artifacts from Github (from the build job)
      uses: actions/download-artifact@v4
      with:
        name: app-artifacts

    - name: Stop the application service
      run: |
        sudo systemctl stop CloudSoft.service        

    - name: Deploy the the application
      run: |
        sudo rm -Rf /opt/CloudSoft || true
        sudo cp -r /home/azureuser/actions-runner/_work/CloudSoft/CloudSoft/ /opt/CloudSoft        

    - name: Start the application service
      run: |
        sudo systemctl start CloudSoft.service        